### ISSUE TITLE
ECMDERR Failed to execute "gulp wiredep"

### ISSUE THREAD

**Issue by himdel** [ManageIQ/manageiq-ui-self_service#85]
Running `gulp wiredep` (or tasks which use it), causes

```
bower ECMDERR Failed to execute "gulp wiredep", exit code of #8 /home/centos/vaneq/manageiq-ui-self_service/node_modules/eslint/node_modules/strip-bom/index.js:2 module.exports = x => { ^ SyntaxError: Unexpected token > at Module.compile (module.js:439:25) at Object.Module.extensions..js (module.js:474:10) at Module.load (module.js:356:32) at Function.Module.load (module.js:312:12) at Module.require (module.js:364:17) at require (module.js:380:17) at Object. (/home/centos/vaneq/manageiq-ui-selfservice/node_modules/eslint/lib/config/config-file.js:23:16) at Module.compile (module.js:456:26) at Object.Module.extensions..js (module.js:474:10) at Module.load (module.js:356:32)

Additional error details:
/home/centos/vaneq/manageiq-ui-self_service/node_modules/eslint/node_modules/strip-bom/index.js:2
module.exports = x => {
^
SyntaxError: Unexpected token >
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (/home/centos/vaneq/manageiq-ui-self_service/node_modules/eslint/lib/config/config-file.js:23:16)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
```

Related eslint issue: https://github.com/eslint/eslint/issues/6607.

This is caused by `strip-bom` starting to use ES6 arrow functions, supported only in node 4+ (4 is a but uncertain..).

**Comment by himdel** [comment]
We can either force the package to the older version, or upgrade node.. for darga, the first option is probably the right one..

**Comment by himdel** [comment]
The chain is a bit longer..

we have `plato ^1.4.0` which started resolving to `plato 1.6.0`, which brought in `eslint 3.*`, which depends on `strip-bom 3.0.0`. Plato is a "JavaScript source analysis and visualizer" meaning it's not even strictly necessary to have it in the code, but the minimal fix is:

```diff
-    "plato": "^1.4.0",
+    "plato": "~1.4.0",
```
